# 🧩 Sudoku Grid Validator using NumPy

A practical NumPy project for validating a 9×9 Sudoku grid using:

- NumPy arrays
- Array indexing and slicing
- Row and column validation
- 3×3 block extraction
- Array sorting and comparison
- Boolean validation logic

### Objective

To verify whether a completed Sudoku grid satisfies all
standard row, column, and 3×3 block constraints.

In [67]:
# ============================================================
# 01. IMPORT NUMPY
# ============================================================

import numpy as np

print("=" * 55)
print("              SUDOKU GRID VALIDATOR")
print("=" * 55)
print("NumPy imported successfully.")

              SUDOKU GRID VALIDATOR
NumPy imported successfully.


In [68]:
# ============================================================
# 02. CREATE SUDOKU GRID
# ============================================================

sudoku = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

print("Sudoku grid created successfully.")
print(f"Grid Shape : {sudoku.shape}")
print(f"Total Cells: {sudoku.size}")

Sudoku grid created successfully.
Grid Shape : (9, 9)
Total Cells: 81


In [69]:
# ============================================================
# 03. DISPLAY SUDOKU GRID
# ============================================================

print("\n" + "=" * 55)
print("                    SUDOKU GRID")
print("=" * 55)

for row_index, row in enumerate(sudoku):

    if row_index % 3 == 0 and row_index != 0:
        print("-" * 21)

    print(
        f"{row[0]} {row[1]} {row[2]} | "
        f"{row[3]} {row[4]} {row[5]} | "
        f"{row[6]} {row[7]} {row[8]}"
    )

print("=" * 55)


                    SUDOKU GRID
5 3 4 | 6 7 8 | 9 1 2
6 7 2 | 1 9 5 | 3 4 8
1 9 8 | 3 4 2 | 5 6 7
---------------------
8 5 9 | 7 6 1 | 4 2 3
4 2 6 | 8 5 3 | 7 9 1
7 1 3 | 9 2 4 | 8 5 6
---------------------
9 6 1 | 5 3 7 | 2 8 4
2 8 7 | 4 1 9 | 6 3 5
3 4 5 | 2 8 6 | 1 7 9


In [70]:
# ============================================================
# 04. CALCULATE OVERALL SUM
# ============================================================

overall_sum = np.sum(sudoku)

print("\n" + "=" * 55)
print("                GRID SUMMARY")
print("=" * 55)

print(f"Total number of cells : {sudoku.size}")
print(f"Overall grid sum      : {overall_sum}")
print("=" * 55)


                GRID SUMMARY
Total number of cells : 81
Overall grid sum      : 405


In [71]:
# Columns'  Sum 
print("\n==============================================")
print(f"🚨 RESULT: SUM OF SUDUKO Columns ARE: {np.sum(s, axis =0)}")
print("==============================================")
c = np.sum(s, axis =0)
for i in c:
    if i != 45: 
        print("❌ Suduko Columns are Invalid")
        break
else:
    print("✅ All Columns are Valid (contain unique 1-9 elements).")


🚨 RESULT: SUM OF SUDUKO Columns ARE: [45 45 45 45 45 45 45 45 45]
✅ All Columns are Valid (contain unique 1-9 elements).


In [72]:
# ============================================================
# 05. VALIDATE ROWS
# ============================================================

expected_numbers = np.arange(1, 10)

valid_rows = True

print("\n" + "=" * 55)
print("                  ROW VALIDATION")
print("=" * 55)

for index, row in enumerate(sudoku, start=1):

    sorted_row = np.sort(row)

    if np.array_equal(sorted_row, expected_numbers):
        print(f"✅ Row {index:02d}: Valid")
    else:
        print(f"❌ Row {index:02d}: Invalid")
        valid_rows = False

print("-" * 55)

if valid_rows:
    print("RESULT: All 9 rows are valid.")
else:
    print("RESULT: One or more rows are invalid.")

print("=" * 55)


                  ROW VALIDATION
✅ Row 01: Valid
✅ Row 02: Valid
✅ Row 03: Valid
✅ Row 04: Valid
✅ Row 05: Valid
✅ Row 06: Valid
✅ Row 07: Valid
✅ Row 08: Valid
✅ Row 09: Valid
-------------------------------------------------------
RESULT: All 9 rows are valid.


In [73]:
# ============================================================
# 06. VALIDATE COLUMNS
# ============================================================

valid_columns = True

print("\n" + "=" * 55)
print("                COLUMN VALIDATION")
print("=" * 55)

for index, column in enumerate(sudoku.T, start=1):

    sorted_column = np.sort(column)

    if np.array_equal(sorted_column, expected_numbers):
        print(f"✅ Column {index:02d}: Valid")
    else:
        print(f"❌ Column {index:02d}: Invalid")
        valid_columns = False

print("-" * 55)

if valid_columns:
    print("RESULT: All 9 columns are valid.")
else:
    print("RESULT: One or more columns are invalid.")

print("=" * 55)


                COLUMN VALIDATION
✅ Column 01: Valid
✅ Column 02: Valid
✅ Column 03: Valid
✅ Column 04: Valid
✅ Column 05: Valid
✅ Column 06: Valid
✅ Column 07: Valid
✅ Column 08: Valid
✅ Column 09: Valid
-------------------------------------------------------
RESULT: All 9 columns are valid.


In [74]:
# ============================================================
# 07. EXTRACT 3x3 BLOCKS
# ============================================================

blocks = []

for row in range(0, 9, 3):
    for column in range(0, 9, 3):

        block = sudoku[row:row + 3, column:column + 3]
        blocks.append(block)

print("\n" + "=" * 55)
print("              SUDOKU 3x3 BLOCKS")
print("=" * 55)

for index, block in enumerate(blocks, start=1):

    print(f"\nBlock {index:02d}:")
    print(block)

print("=" * 55)


              SUDOKU 3x3 BLOCKS

Block 01:
[[5 3 4]
 [6 7 2]
 [1 9 8]]

Block 02:
[[6 7 8]
 [1 9 5]
 [3 4 2]]

Block 03:
[[9 1 2]
 [3 4 8]
 [5 6 7]]

Block 04:
[[8 5 9]
 [4 2 6]
 [7 1 3]]

Block 05:
[[7 6 1]
 [8 5 3]
 [9 2 4]]

Block 06:
[[4 2 3]
 [7 9 1]
 [8 5 6]]

Block 07:
[[9 6 1]
 [2 8 7]
 [3 4 5]]

Block 08:
[[5 3 7]
 [4 1 9]
 [2 8 6]]

Block 09:
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [75]:
# ============================================================
# 08. VALIDATE 3x3 BLOCKS
# ============================================================

valid_blocks = True

print("\n" + "=" * 55)
print("                BLOCK VALIDATION")
print("=" * 55)

for index, block in enumerate(blocks, start=1):

    flattened_block = block.flatten()
    sorted_block = np.sort(flattened_block)

    if np.array_equal(sorted_block, expected_numbers):
        print(f"✅ Block {index:02d}: Valid")
    else:
        print(f"❌ Block {index:02d}: Invalid")
        valid_blocks = False

print("-" * 55)

if valid_blocks:
    print("RESULT: All 9 blocks are valid.")
else:
    print("RESULT: One or more blocks are invalid.")

print("=" * 55)


                BLOCK VALIDATION
✅ Block 01: Valid
✅ Block 02: Valid
✅ Block 03: Valid
✅ Block 04: Valid
✅ Block 05: Valid
✅ Block 06: Valid
✅ Block 07: Valid
✅ Block 08: Valid
✅ Block 09: Valid
-------------------------------------------------------
RESULT: All 9 blocks are valid.


In [76]:
# ============================================================
# 09. COMPLETE SUDOKU VALIDATION
# ============================================================

sudoku_is_valid = (
    valid_rows
    and valid_columns
    and valid_blocks
)

print("\n" + "=" * 55)
print("            COMPLETE VALIDATION")
print("=" * 55)

print(f"Rows       : {'VALID' if valid_rows else 'INVALID'}")
print(f"Columns    : {'VALID' if valid_columns else 'INVALID'}")
print(f"3x3 Blocks : {'VALID' if valid_blocks else 'INVALID'}")

print("-" * 55)

if sudoku_is_valid:
    print("STATUS: Sudoku grid is completely valid. ✅")
else:
    print("STATUS: Sudoku grid is invalid. ❌")

print("=" * 55)


            COMPLETE VALIDATION
Rows       : VALID
Columns    : VALID
3x3 Blocks : VALID
-------------------------------------------------------
STATUS: Sudoku grid is completely valid. ✅


In [77]:
# ============================================================
# 10. FINAL RESULT
# ============================================================

print("\n")
print("╔" + "═" * 53 + "╗")
print("║" + " " * 16 + "FINAL RESULT" + " " * 25 + "║")
print("╠" + "═" * 53 + "╣")

if sudoku_is_valid:
    print("║" + " " * 11 + "🎉 SUDOKU GRID IS VALID" + " " * 19 + "║")
    print("║" + " " * 7 + "All rows, columns, and 3x3 blocks passed." + " " * 4 + "║")
else:
    print("║" + " " * 11 + "❌ SUDOKU GRID IS INVALID" + " " * 17 + "║")
    print("║" + " " * 9 + "One or more validation checks failed." + " " * 7 + "║")

print("╚" + "═" * 53 + "╝")



╔═════════════════════════════════════════════════════╗
║                FINAL RESULT                         ║
╠═════════════════════════════════════════════════════╣
║           🎉 SUDOKU GRID IS VALID                   ║
║       All rows, columns, and 3x3 blocks passed.    ║
╚═════════════════════════════════════════════════════╝
